### PR TITLE
add support for hooks functions, setting query from URL, search exclusion

### PR DESCRIPTION
**Pull request by bobheadxi**
* Add support for `external` results, which opens the result in a new tab
* Add support for `functions`, which provides an implementable interface for various hooks:
   * `processSuggestions` to augment, adjust, or manipulate the suggestions
   * `onGoToSuggestion` to perform actions whenever a result is clicked
* Add support for the fontmatter property `search: false` to exclude a page from results
* Add support for URL search parameter `query` for populating and focusing the search bar

### CODE REVIEW

**Comment by leo-buneev** [comment]
Thanks! That feature looks sweet, let's make it official.

I'd prefer to add more abstract hook `processSuggestions(suggestions, queryString, queryTerms)` in vuepress's settings, that will return new array of suggestions - can be useful for many scenarios, including yours

**Comment by bobheadxi** [comment]
@leo-buneev I'd be happy to - will update this PR and ping you with a nicer implementation 🚀

**Comment by bobheadxi** [comment]
@leo-buneev unfortunately, 5279837 is the only practical way to implement this API within the Vuepress plugin framework - let me know what you think!

**Comment by leo-buneev** [comment]
Wow, that looks more complicated than I thought. Later today I'll try to implement option as a regular function (still can't believe it isn't possible 😮), and if I'll be unsuccessfull will merge your PR.

**Comment by bobheadxi** [comment]
Yeah I couldn't find a way to "persist" a user-provided function for callback :(

**Comment by bobheadxi** [comment]
@leo-buneev For our purposes I've expanded the API in fdeed1f to allow an onclick callback as well - I made the poor choice of opening the PR from a master branch, so please let me know if you would like me to make more granular PRs or just continue expanding on this feature in my fork :)

**Comment by leo-buneev** [comment]
Feel free to continue here, it can be considered as part of the same feature

**Comment by bobheadxi** [comment]
@leo-buneev any chance this might land one day? :) We've been running this in https://docs.ubclaunchpad.com/ with [some non-trivial traffic](https://app.usefathom.com/share/oemmhhle/docs.ubclaunchpad.com) for quite a while

**Comment by bobheadxi** [comment]
@leo-buneev I've cleaned up the PR description and documentation!

**Pull request merged**
